# -*- coding: utf-8 -*-
"""PROVA-PTHON-AULA1-MODULO-EXTRA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gSWS597ideLBd0NySdu79nyQgog52htr

PY-A01]Faça um programa em Python que, utilizando estruturas de repetição, calcule a média de idade dos alunos de uma turma. O programa deve pedir ao usuário a quantidade de alunos na turma e, em seguida, solicitar a idade de cada um. O programa deve utilizar um laço FOR para receber as idades dos alunos e um laço WHILE para realizar a soma das idades. Ao final, o programa deve exibir a média de idade da turma.
"""

n_alunos = int (input("Informe por favor o número de alunos da turma: "))

contador = 0
soma_idade = 0
lista_alunos = []
for aluno in range(n_alunos):
    nome = input (f"Digite o nome do aluno com índice {aluno}: ")
    idade = int(input (f"Digite a idade do aluno com índice {aluno}: "))

    turma = {"Indice_aluno":aluno,
             "Nome": " ",
             "Idade":" "}
    turma["Indice_aluno"] = aluno
    turma["Nome"] = nome
    turma["Idade"] = idade
    lista_alunos.append(turma)
print(lista_alunos)
while contador < n_alunos:
  soma_idade = soma_idade + lista_alunos[contador]["Idade"]
  contador+=1
media = soma_idade / n_alunos
print(f"A média das idades dos alunos é {media}")